### ISSUE TITLE
CRUD of programmes/clubs based on the available programme types 

### ISSUE THREAD

**Issue by luNsindane** [sobantu-technologies/abantu#17]
- [ ] Define Use Cases using mark down

- [ ] Design Activity Diagram using draw io

- [ ] Define Database Structure in visual studio and or draw io

- [ ] Design User Interface Mock ups using draw io 

- [ ] Define test case for use case

- [ ] implement views based on mock up 

- [ ] implement back end to support views

- [ ] write unit test for code written

- [ ] manually test code

**Comment by CelumusaZuma** [comment]
Guys, having CRUD of programmes/clubs based on the available programme types isn't a repetition of what we have already?

**Comment by Ryan-ED** [comment]
Thanks for your comment, @CelumusaZuma . Yes we already have CRUD for programmes/ clubs. But the documentation has to be improved. That is the use case diagrams as well as activity diagrams and use case descriptions. Don't forget to use the documentation on Github so that we can all see the changes you make. 👍

**Comment by CelumusaZuma** [comment]
Okay. Thanks Ryan.
