### ISSUE TITLE
 CRUD of committees which are groups of members 

### ISSUE THREAD

**Issue by luNsindane** [sobantu-technologies/abantu#19]
- [x] Define Use Cases using mark down

- [x] Design Activity Diagram using draw io

- [x] Define Database Structure in visual studio and or draw io

- [x] Design User Interface Mock ups using draw io 

- [ ] Define test case for use case

- [x] implement views based on mock up 

- [x] implement back end to support views

- [ ] write unit test for code written

- [x] manually test code

- [ ] Create user manual
