### ISSUE TITLE
 CRUD of branches which belong to the organisation

### ISSUE THREAD

**Issue by luNsindane** [sobantu-technologies/abantu#20]
- [x] Define Use Cases using mark down

- [ ] Design Activity Diagram using draw io

- [x] Define Database Structure in visual studio and or draw io

- [x] Design User Interface Mock ups using draw io 

- [ ] Define test case for use case

- [ ] implement views based on mock up 

- [ ] implement back end to support views

- [ ] write unit test for code written

- [ ] manually test code

- [ ]  create user manual
