### ISSUE TITLE
Allow for creation of meetings for committees

### ISSUE THREAD

**Issue by sobantu** [sobantu-technologies/abantu#27]
- [x] Define use case description using table template (save as html filtered)

- [x] Design use case diagram using draw io

- [x] Design Activity Diagram using draw io

- [x] Define Database Structure in visual studio and draw io

- [x] Design User Interface Mock ups using draw io 

- [ ] Define test case for use case 

- [x] Commit and push all documentation to the GitHub wiki with appropriate names in appropriate folders and formats (i.e. HTML Filtered, XML, MD)

- [ ] implement views based on mock up 

- [ ] implement back end to support views

- [x] write unit test for code written

- [x] manually test code

- [ ]  create user manual
